-- Purpose: create staging table for processed T-100 route-carrier-month data.
-- Role:
    -- Serves as the landing zone for CSV data generated by the Python preprocessing pipeline.
    -- Staging tables use flexible data types to simplify ingestion and are later transformed into analytics-ready tables in the warehouse.
-- Notes:
    -- Numeric metrics are stored as DOUBLE PRECISION to avoid CSV import type conflicts.
    -- Values are cast to INTEGER during the fact table load step.
    -- load_ts records when the row was inserted into staging.

CREATE TABLE IF NOT EXISTS stg_t100_route_carrier_month (
    year SMALLINT,
    month SMALLINT,
    route_id TEXT,
    unique_carrier TEXT,
    flights_count DOUBLE PRECISION,
    passengers DOUBLE PRECISION,
    seats DOUBLE PRECISION,
    distance_km DOUBLE PRECISION,
    load_ts TIMESTAMPTZ DEFAULT NOW()
);